<div>
    <div class="max-w-7xl mx-auto py-10 sm:px-6 lg:px-8">
        @if(empty($paymentMethod) || $paymentMethod->nanoAddresses->count() == 0)
            <payment-method-nano-setup></payment-method-nano-setup>
        @endif

        @if(!empty($paymentMethod) && $paymentMethod->nanoAddresses->count() > 0)

            <h3 class="text-lg leading-6 font-bold text-gray-900 mb-4">
                Where should we send funds when consolidating?
            </h3>
            <div class="bg-white shadow overflow-hidden sm:rounded-md p-4">
                <p class="text-grey-dark mb-4 text-sm">Enter your nano address that all funds will be forwarded to. This should be your personal address and not one generated by CoinEmbed.</p>
                <div>
                    <field-group>
                        <field-label :required="true">Nano Address</field-label>
                        <field-input-text placeholder="nano_" wire:model="consolidationAddress" required="required"></field-input-text>
                    </field-group>
                </div>
                <button-ui theme="primary" wire:click="$emit('save')">Save Settings</button-ui>
            </div>

                <div class="py-4 text-right">
                    <button-ui size="sm" onclick="confirm('This will delete all accounts associated with the current seed. Are you sure you want to start over?') || event.stopImmediatePropagation()" theme="danger" wire:click="deleteAccounts">Delete accounts and create a new seed</button-ui>
                </div>

                <?php
                // TODO - If $accountsSaved and has consolidation address, show consolidation tool (show any pending money) (import wordlist and run all)
                ?>

                @if(!empty($this->consolidationAddress))
                    <hr class="border-t-4 border-gray-200 mt-6 mb-6" />
                    <livewire:account.payment-method.nano.consolidator consolidation-address="{{ $consolidationAddress }}" />
                @endif

        @endif



    </div>
</div>
